mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'
proxies:
proxy-providers:
  N3RO:
    type: http
    url: ""
    path: ./proxy_providers/N3RO.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  GaCloud:
    type: http
    url: ""
    path: ./proxy_providers/GaCloud.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - N3RO
      - GaCloud
  - name: N3RO
    type: select
    use:
      - N3RO
  - name: GaCloud
    type: select
    use:
      - GaCloud
  - name: Others
    type: select
    proxies:
      - Proxy
      - DIRECT

rule-providers:
  AD:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml
    path: ./rule_providers/Ad.yaml
    interval: 21600
  Google:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
    path: ./rule_providers/Google.yaml
    interval: 21600
  Proxy:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/wasdjkl/clash-rules/master/Proxy.yaml
    path: ./rule_providers/Proxy.yaml
    interval: 21600
  Direct:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/wasdjkl/clash-rules/master/Direct.yaml
    path: ./rule_providers/Direct.yaml
    interval: 21600
  Local:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/wasdjkl/clash-rules/master/Locale.yaml
    path: ./rule_providers/Locale.yaml
    interval: 21600

rules:
  - RULE-SET,Local,DIRECT,no-resolve
  - RULE-SET,AD,REJECT
  - RULE-SET,Direct,DIRECT
  - RULE-SET,Google,Proxy
  - RULE-SET,Proxy,Proxy
  - GEOIP,CN,DIRECT
  - MATCH,Others